### ISSUE TITLE
Outsource code for basic Wikidata curation/parsing

### ISSUE THREAD

**Issue by lubianat** [lubianat/pyorcidator#15]
I've create a package for basic Wikidata curation tools: 
 - https://github.com/lubianat/wdcuration

I use them across various projects. I'll adapt pyorcidator to use functions from that package, but I am a bit unsure on how to best do that. 

Perhaps I'll push a version of wdcuration to PyPi and add it as a requirement. Anyone has thoughts on that?

**Comment by jvfe** [comment]
Great idea for decoupling and generalizing the code!

> Perhaps I'll push a version of wdcuration to PyPi and add it as a requirement. Anyone has thoughts on that?

That's how I'd go about it, yes. I believe it to be the best way to do it.
