### ISSUE TITLE
Pull DOIs from ORCID

### ISSUE THREAD

**Issue by lubianat** [lubianat/pyorcidator#22]

**Comment by jvfe** [comment]
Is this done, @lubianat? Given [280a74b](https://github.com/lubianat/pyorcidator/commit/280a74bbda0dea51bb32977c8f25f970aa81d97f) is in the main branch (function get_paper_dois).

If so, I'll probably use the function to implement #28

**Comment by jvfe** [comment]
Just tested and get_paper_dois seems to still work, you just have to pass it `data["activities-summary"]["works"]["group"]` as input.

**Comment by jvfe** [comment]
Closing this as the function works as expected.
