### ISSUE TITLE
Parse websites and social links

### ISSUE THREAD

**Issue by lubianat** [lubianat/pyorcidator#37]
e.g. see https://orcid.org/0000-0002-5292-4083

**Comment by cthoyt** [comment]
Excellent idea. btw I had started a branch over the weekend that was using pydantic to parse the ORCID results that might make programming all of this easier

https://github.com/lubianat/pyorcidator/tree/orcid-model

**Comment by cthoyt** [comment]
I am really surprised how hard it is to use the ORCID API... their data model makes so little sense
