### ISSUE TITLE
Add keywords as "field of work" statements

### ISSUE THREAD

**Issue by lubianat** [lubianat/pyorcidator#38]
e.g https://orcid.org/0000-0002-6049-9865

**Comment by jvfe** [comment]
I'll try working on this

**Comment by cthoyt** [comment]
@jvfe maybe you can also use a similar concept as in #36 to identify a high-level wikidata term that most fields of work / topics are a subclass of, and then we can automatically pull them down and pre-populate a dictionary.

**Comment by jvfe** [comment]
Sounds like a good idea. The same logic in #36 would probably work for this, would just have to change Q189533 (academic degree) for something like Q11862829 (academic discipline).

I'll try it out, thanks!

**Comment by cthoyt** [comment]
@jvfe I just generalized the code from #36 in e269d8e so you can easily reuse it.

**Comment by lubianat** [comment]
It is a good idea, we just need to watch out for duplicates. They are already abundant in https://github.com/lubianat/pyorcidator/blob/master/src/pyorcidator/dictionaries/role.json with no easy fix.

**Comment by lubianat** [comment]
I'd rather actually leave it to manual curation until we get a better sense of the diversity.
Automatically adding topics now might add a lot of silent false positives.

**Comment by jvfe** [comment]
> @jvfe are you working on that? I'll start a branch on my own (kind of wan't some hack on this today), but I won't merge anything

Check #48
