### ISSUE TITLE
Improve handling of external links when 'https' not present

### ISSUE THREAD

**Issue by jvfe** [lubianat/pyorcidator#53]
Currently, if an ORCID user doesn't have 'https://' in their social links tab the link isn't recognized by pyorcidator. For example, the github link for https://orcid.org/0000-0001-7542-0286 (github.com/egonw).

This could be probably solved by using a regex instead of the current `rv[key] = url[len(url_prefix) :]`. I might send a possible solution soon.

**Comment by cthoyt** [comment]
Just add special cases with if/else. That will be the most simple
