### ISSUE TITLE
Use a dedicated CLI/TUI library

### ISSUE THREAD

**Issue by jvfe** [lubianat/pyorcidator#6]
The current code is great for hacking around, but if the end-product is a CLI app (If it isn't, disregard this), I'd recommend using something like [Click](https://click.palletsprojects.com/en/8.1.x/), [python-inquirer](https://github.com/magmax/python-inquirer) and [rich](https://github.com/Textualize/rich).

Leaving these here as suggestions for the future.

**Comment by cthoyt** [comment]
We did this in #11 😄

**Comment by jvfe** [comment]
Yep, I saw that, thank you!
