### ISSUE TITLE
Add dictionaries for first and last names (and infer gender)

### ISSUE THREAD

**Issue by lubianat** [lubianat/pyorcidator#7]
e.g. Rodrigo Dalmolin

Rodrigo - https://www.wikidata.org/wiki/Q4927979 (**male** given name)
Dalmolin - https://www.wikidata.org/wiki/Q37464573  (family name)

From **male** given name, infer sex or gender (P21) --> male

Watchout for:
 - names used for multiple genders (and non-binary names): "Alex", "Andrea" etc

**Comment by lubianat** [comment]
Maybe 3 dicts: 

- given name
- family name
- ambiguous names

**Comment by cthoyt** [comment]
I'm lukewarm about this, there's too much room for ambiguity, an then if you import stuff that's not for sure, wikidata will just reflect the bias of the algorithm/data set you have used. Maybe @egonw also had similar concerns?

**Comment by egonw** [comment]
I'd stay away from gender info.
